spring.application.name: claimnomore

server:
  port: ${SERVER_PORT:8081}

keycloak:
  auth-server-url: http://localhost:8080
  realm: fiap-keycloak

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: "nomeDoSeuBanco"
  mail:
    host: smtp.gmail.com
    port: 587
    username: shinjitanigushi@gmail.com
    password: "sua_senha_ou_app_password"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: dev
  security:
    oauth2:
      client:
        provider:
          fiap-keycloak:
            issuer-uri: http://localhost:8080/realms/fiap-keycloak
        registration:
          keycloak:
            provider: fiap-keycloak
            authorization-grant-type: authorization_code
            client-id: fiap-keycloak-confidential
            client-secret: secret
            scope: openid

  application:
    name: ecommerce-thymeleaf
  thymeleaf:
    cache: false
  http:
    encoding:
      charset: UTF-8
  messages:
    encoding: UTF-8
    basename: messages
  devtools:
    restart:
      enabled: true

logging:
  level:
    root: INFO
    br: DEBUG
